openapi: "3.0.2"
info:
  description: "This is a sample yaml file to work in Microcks."
  version: "1.0.0"
  title: "POC"
paths:
  /createUser:
    post:
      summary: "Create the details of User1"
      description: ""
      operationId: "createUser1"
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              examples:
                UserValueOne:
                  value: '{"id": "3", "name": "Shweta", "nation": "Spain"}'
                UserValueTwo:
                  value: '{"id": "4", "name": "Harleen", "nation": "India"}'
        
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        nation:
           type: "string"
